# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rarecloud < Formula
  desc "RareCloud CLI - manage servers, clusters, billing and account."
  homepage "https://rarecloud.io"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.3.0/rarecloud_0.3.0_darwin_amd64.tar.gz"
      sha256 "0b1eef86e5d247c20c7de4ad6bba3fdb6c15b65c880409c77bbf11f567f4d1d4"

      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.3.0/rarecloud_0.3.0_darwin_arm64.tar.gz"
      sha256 "8d339ff0cb2a04a98dadbc4dc381a7747152c8a46def86cb6c7cdde6dd4e2ded"

      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.3.0/rarecloud_0.3.0_linux_amd64.tar.gz"
      sha256 "ceb1ac7c2c51585ad3422e9219bc83e78e3a04feaacadd4c2f7361fcf028b54a"
      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.3.0/rarecloud_0.3.0_linux_arm64.tar.gz"
      sha256 "2aa0f5ba2f45eabf6616f5253404dfd57be158a7e9713b177e170c3200ec0b2d"
      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
  end

  test do
    system "#{bin}/rarecloud", "--help"
  end
end
