# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rarecloud < Formula
  desc "RareCloud CLI - manage servers, clusters, billing and account."
  homepage "https://rarecloud.io"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.1.1/rarecloud_0.1.1_darwin_amd64.tar.gz"
      sha256 "02b39a08c7032a44f3b88ebd5b1a28a26d814330728cc3352e278ae87c4636af"

      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.1.1/rarecloud_0.1.1_darwin_arm64.tar.gz"
      sha256 "2d30730db4be0bf7aaa1e9c6a33558fd985f23172a42c19cf3e0ec910ca3dfdc"

      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.1.1/rarecloud_0.1.1_linux_amd64.tar.gz"
      sha256 "62625373c1851ba79777d5a0993b84e377700d4d7d2c316ed8dfc67fa68192f0"
      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.1.1/rarecloud_0.1.1_linux_arm64.tar.gz"
      sha256 "58c3ec7d75e7193e51aca760a17adbb8783a08230360e41d505de50c58d3d0a8"
      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
  end

  test do
    system "#{bin}/rarecloud", "--help"
  end
end
