# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rarecloud < Formula
  desc "RareCloud CLI - manage servers, clusters, billing and account."
  homepage "https://rarecloud.io"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.2.0/rarecloud_0.2.0_darwin_amd64.tar.gz"
      sha256 "e132f810868eff257400bd805d771fe36841ea3906dc50cd4ea38fabef83a4f1"

      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.2.0/rarecloud_0.2.0_darwin_arm64.tar.gz"
      sha256 "fd29c12391ba94827b5280d18371fe751d30808fe992c295e99e5036e6a04900"

      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.2.0/rarecloud_0.2.0_linux_amd64.tar.gz"
      sha256 "61904f9d1ae2e979a371b9bc735eb3b22418def573d16aa7cb1f5beac54f40f5"
      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RareCloudio/rarecloud-cli/releases/download/v0.2.0/rarecloud_0.2.0_linux_arm64.tar.gz"
      sha256 "1837c46fcc7677dc1f62adbd729169e9658396c8c0c2040ba4c61a1315b163a2"
      define_method(:install) do
        bin.install "rarecloud"
        bin.install_symlink "rarecloud" => "rcloud"
        bin.install_symlink "rarecloud" => "rare"
      end
    end
  end

  test do
    system "#{bin}/rarecloud", "--help"
  end
end
